### ISSUE TITLE
ui container stuck during start

### ISSUE THREAD

**Issue by Kaibling** [Kaibling/sisyphos#5]
The new ui container appears to be stuck due to missing configuration or something. 
@rolandkulkov 
```
$ docker logs sisyphos-ui-1 

> dev
> next dev -p 5100

- ready started server on 0.0.0.0:5100, url: http://localhost:5100
`destination` does not start with `/`, `http://`, or `https://` for route {"source":"/app/:path*","destination":"undefined/:path*"}


Error: Invalid rewrite found
$ 
```

**Comment by rolandkulkov** [comment]
The missing .env from the ui directory, caused the error, invalid rewrite found.

I have created  a pull request for the fix.

https://github.com/Kaibling/sisyphos/pull/6

**Comment by Kaibling** [comment]
is working
